; ==============================================================================
; V.I.E.R.N.E.S. - Asterisk REST Interface (ARI) Configuration
; ==============================================================================

[general]
enabled = yes
pretty = yes
allowed_origins = *
auth_realm = VIERNES-AI-Telephony

[viernes-ari-user]
type = user
read_only = no
password = ${ENV(ARI_PASSWORD)}
password_format = plain
